version: '3.8'

services:
  # Redis - 快取和 Pub/Sub
  redis:
    image: redis:7-alpine
    container_name: golden-buy-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - golden-buy-network

  # InfluxDB - 時序資料庫
  influxdb:
    image: influxdb:2.7
    container_name: golden-buy-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123456
      - DOCKER_INFLUXDB_INIT_ORG=golden-buy
      - DOCKER_INFLUXDB_INIT_BUCKET=golden_buy
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - golden-buy-network

  # PostgreSQL - 關聯式資料庫
  postgres:
    image: postgres:16-alpine
    container_name: golden-buy-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=golden_buy
      - POSTGRES_PASSWORD=golden_buy_password
      - POSTGRES_DB=golden_buy
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U golden_buy"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - golden-buy-network

  # Grafana - 資料視覺化
  grafana:
    image: grafana/grafana:10.2.0
    container_name: golden-buy-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - golden-buy-network

volumes:
  redis-data:
  influxdb-data:
  postgres-data:
  grafana-data:

networks:
  golden-buy-network:
    driver: bridge

